### ISSUE TITLE
get output files from PCE to web interface

### ISSUE THREAD

**Issue by ssfoley** [ssfoley/onramp#43]
Need to figure out how to get the files from the PCE to the web server, and from the web server to the web interface.

**Comment by koepked** [comment]
The PCE is currently serving this information, but the PCEAccess class in the server implementation needs to be updated to fetch it.

**Comment by ssfoley** [comment]
Closed with commit: 797d3777c0485cdcf07949faa218f10a3beac1e2.

A few other refactoring items included:
- changed users.js to start.js to match start.html
- changed some manual path construction to use os.path.join instead.  much more portable and less error-prone.
