### ISSUE TITLE
AUC module not accounting for number of processes 

### ISSUE THREAD

**Issue by chaseknudson** [ssfoley/onramp#85]
I tried running the AUC module on flux with different numbers of processes and got the same result each time.  I selected 3 processes and the result showed 1 used.

![image](https://cloud.githubusercontent.com/assets/4601221/16181292/c49ab8ca-365e-11e6-8631-f486f0478b88.png)
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by ssfoley** [comment]
What did you use for the mode?  It will only run on one process if it is in OpenMP mode (o) or in Serial mode (s).  If you want multiple processes to be used, then MPI mode needs to be selected (m).  I was able to run with different numbers of processes using MPI mode.  This may just be a problem with validation of parameters or explanation of how to use the module.

**Comment by jarq6c** [comment]
Yes, OpenMP mode and serial mode should only use 1 process. Processes are selectable (relevant) only when using MPI mode or hybrid mode.

**Comment by chaseknudson** [comment]
Okay so for the mode I was using (Serial) it was functioning properly then. So this issue then becomes that there is no validation on the form. Also the order of the form should probably change to make it more intuitive.
