### ISSUE TITLE
OnRamp logo logs the user out

### ISSUE THREAD

**Issue by chaseknudson** [ssfoley/onramp#89]
## Expected Behavior

The button shouldn't log the user out, a few suggestions would be 
- Make the button open a tab to the OnRamp wiki or informational page
- Take the user to the main dashboard
## Current Behavior

When clicking on the "OnRamp" logo in the upper left the user is logged out and there is already a "Logout" button in the upper right. 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by ssfoley** [comment]
just disable as a button.
